name: flutter_isolate
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  get_it: ^7.2.0
  sqflite: ^2.2.4+1
  external_path: ^1.0.3
  fluttertoast: ^8.1.2
  provider: ^6.0.5
  path_provider: ^2.0.11
  dio: ^4.0.6
  permission_handler: ^10.2.0
  open_filex: ^4.3.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  flutter_charts: ^0.5.0
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true